name: Release

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  checkout:
    name: "Checkout"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  testing:
    name: "Testing"
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Tests
        run: swift test

  release-on-push:
    name: "Create release"
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [checkout, testing]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          release_name: "Release <RELEASE_VERSION>"
          max_commits: 100